/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BecomingRouteImport } from './routes/becoming'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as HowIThinkRouteImport } from './routes/how-i-think'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomingRoute = BecomingRouteImport.update({
  id: '/becoming',
  path: '/becoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HowIThinkRoute = HowIThinkRouteImport.update({
  id: '/how-i-think',
  path: '/how-i-think',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/becoming': typeof BecomingRoute
  '/contact': typeof ContactRoute
  '/field-notes': typeof FieldNotesRoute
  '/how-i-think': typeof HowIThinkRoute
  '/linkedin': typeof LinkedinRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/becoming': typeof BecomingRoute
  '/contact': typeof ContactRoute
  '/field-notes': typeof FieldNotesRoute
  '/how-i-think': typeof HowIThinkRoute
  '/linkedin': typeof LinkedinRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/becoming': typeof BecomingRoute
  '/contact': typeof ContactRoute
  '/field-notes': typeof FieldNotesRoute
  '/how-i-think': typeof HowIThinkRoute
  '/linkedin': typeof LinkedinRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/becoming'
    | '/contact'
    | '/field-notes'
    | '/how-i-think'
    | '/linkedin'
    | '/sitemap.xml'
    | '/work/$slug'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/becoming'
    | '/contact'
    | '/field-notes'
    | '/how-i-think'
    | '/linkedin'
    | '/sitemap.xml'
    | '/work/$slug'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/becoming'
    | '/contact'
    | '/field-notes'
    | '/how-i-think'
    | '/linkedin'
    | '/sitemap.xml'
    | '/work/$slug'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomingRoute: typeof BecomingRoute
  ContactRoute: typeof ContactRoute
  FieldNotesRoute: typeof FieldNotesRoute
  HowIThinkRoute: typeof HowIThinkRoute
  LinkedinRoute: typeof LinkedinRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/becoming': {
      id: '/becoming'
      path: '/becoming'
      fullPath: '/becoming'
      preLoaderRoute: typeof BecomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-i-think': {
      id: '/how-i-think'
      path: '/how-i-think'
      fullPath: '/how-i-think'
      preLoaderRoute: typeof HowIThinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomingRoute: BecomingRoute,
  ContactRoute: ContactRoute,
  FieldNotesRoute: FieldNotesRoute,
  HowIThinkRoute: HowIThinkRoute,
  LinkedinRoute: LinkedinRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
